[settings]
# Output directory
output = "Files"

# A minimum id in base36
min_id = "aaaaa"

# A maximum id in base36
# This has to be larger than min_id
max_id = "zzzzzz"

# Global upload limit
upload_limit = "256 MiB"

# You can give this user any name you want
[user.user1]
# Put this in the Authorization header
# For increased security the token should be random and as long as possible
token = "NLhv97y0b+CvQrur5wyIG2SUYjVzKBg3EFbE2xup52EWSw0JnmBkn6ENWP5fOL"

# Every user can have a custom descriptor
# Replaces {name} with the generated id and {ext} with the file extension
# Default: "{name}.{ext}"
descriptor = "user1-{name}.{ext}"

# Overrides the global upload limit for this specific user
# Optional
upload_limit = "20 MiB"

[User.test]
token = "gJHJ5scsmBweSD7Um/kWNmPKFzRc4jtJJ+QO3tR3NEQptqlJPEcMIYAj3FYBJKKhNHGvnPex"